-- Ensure the employee table exists
CREATE TABLE IF NOT EXISTS employee(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)        NOT NULL,
    email         VARCHAR(255) UNIQUE NOT NULL,
    mobile_number BIGINT UNIQUE       NOT NULL,
    address       VARCHAR(255)        NOT NULL,
    date_of_birth DATE                NOT NULL,
    salary        DOUBLE PRECISION    NOT NULL,
    department    VARCHAR(255)        NOT NULL
);

-- Employee 1
INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT 'John Doe',
       'john.doe@example.com',
       9876543210,
       '123 Main St, Springfield',
       '1985-06-15',
       65000,
       'IT'
WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'john.doe@example.com'
);

-- Employee 2
INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT 'Jane Smith',
       'jane.smith@example.com',
       9876543211,
       '456 Elm St, Shelbyville',
       '1990-09-23',
       72000,
       'HR'
WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'jane.smith@example.com'
);

-- Employee 3
INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT 'Alice Johnson',
       'alice.johnson@example.com',
       9876543212,
       '789 Oak St, Capital City',
       '1978-03-12',
       90000,
       'Finance'
WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'alice.johnson@example.com'
);

-- Employee 4
INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT 'Bob Brown',
       'bob.brown@example.com',
       9876543213,
       '321 Pine St, Springfield',
       '1982-11-30',
       80000,
       'Marketing'
WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'bob.brown@example.com'
);

-- Employee 5
INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT 'Emily Davis',
       'emily.davis@example.com',
       9876543214,
       '654 Maple St, Shelbyville',
       '1995-02-05',
       58000,
       'Sales'
WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'emily.davis@example.com'
);

-- Employee 6
INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT 'Michael Green',
       'michael.green@example.com',
       9876543215,
       '987 Cedar St, Springfield',
       '1988-07-25',
       76000,
       'IT'
WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'michael.green@example.com'
);

-- Employee 7
INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT 'Sarah Taylor',
       'sarah.taylor@example.com',
       9876543216,
       '123 Birch St, Shelbyville',
       '1992-04-18',
       68000,
       'HR'
WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'sarah.taylor@example.com'
);

-- Employee 8
INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT 'David Wilson',
       'david.wilson@example.com',
       9876543217,
       '456 Ash St, Capital City',
       '1975-01-11',
       105000,
       'Management'
WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'david.wilson@example.com'
);

-- Employee 9
INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT 'Laura White',
       'laura.white@example.com',
       9876543218,
       '789 Palm St, Springfield',
       '1989-09-02',
       74000,
       'Finance'
WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'laura.white@example.com'
);

-- Employee 10
INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT 'James Harris',
       'james.harris@example.com',
       9876543219,
       '321 Cherry St, Shelbyville',
       '1993-11-15',
       61000,
       'Sales'
WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'james.harris@example.com'
);

-- Employee 11
INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT 'Emma Moore',
       'emma.moore@example.com',
       9876543220,
       '654 Spruce St, Capital City',
       '1980-08-09',
       88000,
       'Marketing'
WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'emma.moore@example.com'
);

-- Employee 12
INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT 'Ethan Martinez',
       'ethan.martinez@example.com',
       9876543221,
       '987 Redwood St, Springfield',
       '1984-05-03',
       92000,
       'IT'
WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'ethan.martinez@example.com'
);

-- Employee 13
INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT 'Sophia Clark',
       'sophia.clark@example.com',
       9876543222,
       '123 Hickory St, Shelbyville',
       '1991-12-25',
       70000,
       'HR'
WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'sophia.clark@example.com'
);

-- Employee 14
INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT 'Daniel Lewis',
       'daniel.lewis@example.com',
       9876543223,
       '456 Cypress St, Capital City',
       '1976-06-08',
       99000,
       'Finance'
WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'daniel.lewis@example.com'
);

-- Employee 15
INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT 'Isabella Walker',
       'isabella.walker@example.com',
       9876543224,
       '789 Willow St, Springfield',
       '1987-10-17',
       81000,
       'Sales'
WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'isabella.walker@example.com'
);