-- Ensure the 'employee' table exists
CREATE TABLE IF NOT EXISTS employee
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL UNIQUE,
    mobile_number   BIGINT NOT NULL UNIQUE,
    address         VARCHAR(255) NOT NULL,
    date_of_birth   DATE NOT NULL,
    salary          DOUBLE PRECISION NOT NULL,
    department      VARCHAR(255) NOT NULL
    );

-- Insert sample employees
INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT
    'John Doe',
    'john.doe@example.com',
    9876543210,
    '123 Main St, Springfield',
    '1985-06-15',
    65000.00,
    'Engineering'
    WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'john.doe@example.com'
);

INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT
    'Jane Smith',
    'jane.smith@example.com',
    9876543211,
    '456 Elm St, Shelbyville',
    '1990-09-23',
    72000.00,
    'Human Resources'
    WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'jane.smith@example.com'
);

INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT
    'Alice Johnson',
    'alice.johnson@example.com',
    9876543212,
    '789 Oak St, Capital City',
    '1978-03-12',
    85000.00,
    'Finance'
    WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'alice.johnson@example.com'
);

INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT
    'Bob Brown',
    'bob.brown@example.com',
    9876543213,
    '321 Pine St, Springfield',
    '1982-11-30',
    68000.00,
    'Marketing'
    WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'bob.brown@example.com'
);

INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT
    'Emily Davis',
    'emily.davis@example.com',
    9876543214,
    '654 Maple St, Shelbyville',
    '1995-02-05',
    61000.00,
    'Sales'
    WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'emily.davis@example.com'
);

INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT
    'Michael Green',
    'michael.green@example.com',
    9876543215,
    '987 Cedar St, Springfield',
    '1988-07-25',
    77000.00,
    'Engineering'
    WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'michael.green@example.com'
);

INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT
    'Sarah Taylor',
    'sarah.taylor@example.com',
    9876543216,
    '123 Birch St, Shelbyville',
    '1992-04-18',
    64000.00,
    'Customer Support'
    WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'sarah.taylor@example.com'
);

INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT
    'David Wilson',
    'david.wilson@example.com',
    9876543217,
    '456 Ash St, Capital City',
    '1975-01-11',
    93000.00,
    'Management'
    WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'david.wilson@example.com'
);

INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT
    'Laura White',
    'laura.white@example.com',
    9876543218,
    '789 Palm St, Springfield',
    '1989-09-02',
    70000.00,
    'Operations'
    WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'laura.white@example.com'
);

INSERT INTO employee (name, email, mobile_number, address, date_of_birth, salary, department)
SELECT
    'James Harris',
    'james.harris@example.com',
    9876543219,
    '321 Cherry St, Shelbyville',
    '1993-11-15',
    66000.00,
    'Information Technology'
    WHERE NOT EXISTS (
    SELECT 1 FROM employee WHERE email = 'james.harris@example.com'
);