apiVersion: 1

datasources:

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        # This links TraceId in logs directly to Zipkin traces
        - matcherRegex: "traceId=(\\w+)"
          name: TraceID
          url: "http://localhost:9411/zipkin/traces/${__value.raw}"
          datasourceUid: zipkin

  - name: Zipkin
    type: zipkin
    access: proxy
    url: http://zipkin:9411
    uid: zipkin
    editable: true